services:

  golang-hdi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GO_VERSION=1.24.0
        - USER_NAME=vscode
    network_mode: "host"
    volumes:
      - ../..:/workspaces:cached      
    command: sleep infinity

